#!/usr/bin/env ruby
require '../../lib/docwu'

# docwu 的配置
Docwu.configure do |config|
  config.src_paths          = {
    'doc1' => "#{File.dirname(__FILE__)}/resources/doc1",
    'doc2' => "#{File.dirname(__FILE__)}/resources/doc2"
  }

  config.asset_paths = ["#{File.dirname(__FILE__)}/resources/assets"]
  config.layout_paths = ["#{File.dirname(__FILE__)}/resources/layouts"]

  config.output_path        = "#{File.dirname(__FILE__)}/resources/output"                       # HTML输出的地方
end

# 输入html
Docwu.generate

Docwu::Server.process
