#!/usr/bin/env ruby
require '../../lib/docwu'

# docwu 的配置
Docwu.configure do |config|
  config.src_paths          = {
    'doc1' => "#{File.dirname(__FILE__)}/resources/doc1",
    'doc2' => "#{File.dirname(__FILE__)}/resources/doc2"
  }

  config.asset_paths = ["#{File.dirname(__FILE__)}/resources/assets"]
  config.layout_paths = ["#{File.dirname(__FILE__)}/resources/layouts"]

  config.output_path        = "#{File.dirname(__FILE__)}/resources/output"                       # HTML输出的地方

  config.data = {
    'copyright' => {
      "year" => '2012 - 2013',
      "name" => "文档大全",
      "content" => "这里有大量的文档"
    }
  }
end

# 输入html
Docwu.generate

Docwu::Server.process
